;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-forward-char
	hydra-multiple-cursors/mc/add-cursor-on-click
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-next-line
	evil-previous-line
	hydra-multiple-cursors/ignore
	))
